#include "fastvessels/common.hpp"
#include "fastvessels/config.hpp"
#include "fastvessels/env_info.hpp"
#include "fastvessels/postprocess.hpp"
#include "fastvessels/preprocess.hpp"
#include "fastvessels/solver.hpp"

#include <fstream>
#include <iomanip>
#include <iostream>
#include <vector>

namespace {

fastvessels::SolverConfig ParseArgs(int argc, char** argv, const fastvessels::SolverConfig& defaults) {
	fastvessels::SolverConfig config = defaults;
	std::vector<std::string> args(argv + 1, argv + argc);
	for (size_t i = 0; i < args.size(); ++i) {
		if (args[i] == "--config" && i + 1 < args.size()) {
			config.config_path = args[++i];
		} else if (args[i] == "--mode" && i + 1 < args.size()) {
			config.mode = fastvessels::ToLower(args[++i]);
		} else if (args[i] == "--feature" && i + 1 < args.size()) {
			config.feature = fastvessels::ToLower(args[++i]);
		} else if (args[i] == "--use-mpi" && i + 1 < args.size()) {
			config.use_mpi = fastvessels::ToLower(args[++i]);
		} else if (args[i] == "--cpu-threads" && i + 1 < args.size()) {
			config.cpu_threads = static_cast<int>(fastvessels::ParseInt(args[++i], config.cpu_threads));
		} else if (args[i] == "--gpus" && i + 1 < args.size()) {
			config.num_gpus = static_cast<int>(fastvessels::ParseInt(args[++i], config.num_gpus));
		} else if (args[i] == "--min-cpu-for-gpu" && i + 1 < args.size()) {
			config.min_cpu_for_gpu = static_cast<int>(fastvessels::ParseInt(args[++i], config.min_cpu_for_gpu));
		} else if (args[i] == "--gpu-work-fraction" && i + 1 < args.size()) {
			config.gpu_work_fraction = fastvessels::ParseDouble(args[++i], config.gpu_work_fraction);
		} else if (args[i] == "--work-items" && i + 1 < args.size()) {
			config.work_items = static_cast<std::uint64_t>(std::max(1LL, fastvessels::ParseInt(args[++i], static_cast<long long>(config.work_items))));
		} else if (args[i] == "--inner-iters" && i + 1 < args.size()) {
			config.inner_iters = static_cast<std::uint32_t>(std::max(1LL, fastvessels::ParseInt(args[++i], static_cast<long long>(config.inner_iters))));
		} else if (args[i] == "--repetitions" && i + 1 < args.size()) {
			config.repetitions = static_cast<int>(std::max(1LL, fastvessels::ParseInt(args[++i], config.repetitions)));
		} else if (args[i] == "--results" && i + 1 < args.size()) {
			config.results_output = args[++i];
		} else if (args[i].rfind("--", 0) != 0 && config.config_path == defaults.config_path) {
			config.config_path = args[i];
		}
	}
	return config;
}

void LogPreprocessSummary(const fastvessels::PreprocessResult& result) {
	std::cout << "Preprocessing complete" << std::endl;
	std::cout << "Best option: feature=" << result.best_config.feature
			  << " cpu_threads=" << result.best_config.cpu_threads
			  << " num_gpus=" << result.best_config.num_gpus
			  << " time_s=" << std::fixed << std::setprecision(6) << result.best_result.seconds
			  << " items_per_s=" << std::fixed << std::setprecision(2) << fastvessels::ThroughputItemsPerSecond(result.best_result)
			  << std::endl;
}

} // namespace

int main(int argc, char** argv) {
	fastvessels::SolverConfig defaults;
	fastvessels::SolverConfig config = ParseArgs(argc, argv, defaults);

	fastvessels::CpuInfo cpu = fastvessels::DetectCpuInfo();
	fastvessels::GpuInfo gpu = fastvessels::DetectGpuInfo();
	fastvessels::MpiInfo mpiEnv = fastvessels::DetectMpiInfoFromEnv();
	bool useMpi = fastvessels::ShouldUseMpi(config, mpiEnv);
	fastvessels::MpiInfo mpi = useMpi ? mpiEnv : fastvessels::MpiInfo{};

	std::ifstream existing(config.config_path);
	if (!existing.good()) {
		if (mpi.rank == 0) {
			std::cout << "Preprocessing: initializing solver_input.txt" << std::endl;
			fastvessels::WriteConfigFile(config.config_path, config, cpu, gpu, mpi, "Solver configuration (generated by multiblock)");
			std::cout << "Generated config: " << config.config_path << std::endl;
		}
	} else {
		config = fastvessels::LoadConfig(config.config_path, config);
	}

	if (fastvessels::ToLower(config.mode) == "preprocess") {
		auto result = fastvessels::RunPreprocess(config, cpu, gpu, mpi);
		if (mpi.rank == 0) {
			fastvessels::WriteConfigFile(config.config_path, result.best_config, cpu, gpu, mpi,
				"Solver configuration (updated by preprocess)");
			std::cout << "Updating config file..." << std::endl;
			LogPreprocessSummary(result);
		}
		return 0;
	}

	if (mpi.rank == 0) {
		std::cout << "Detected CPU logical_cores=" << cpu.logical;
		if (cpu.physical > 0) {
			std::cout << " physical_cores=" << cpu.physical;
		}
		std::cout << std::endl;
		std::cout << "Detected GPU devices=" << gpu.count;
		if (gpu.cores > 0) {
			std::cout << " gpu_cores=" << gpu.cores;
		}
		if (!gpu.name.empty()) {
			std::cout << " name=\"" << gpu.name << "\"";
		}
		std::cout << std::endl;
		const auto& featureSpec = fastvessels::ResolveFeatureSpec(config.feature);
		if (featureSpec.uses_gpu && gpu.count == 0) {
			std::cout << "Note: GPU feature requested but no GPU detected. "
					  << "This build uses a CPU fallback for GPU workers." << std::endl;
		}
	}

	if (mpi.rank == 0) {
		std::cout << "Running simulation..." << std::endl;
	}
	auto result = fastvessels::RunBenchmark(config, cpu, gpu, mpi);
	if (mpi.rank == 0) {
		fastvessels::WriteResults(config.results_output, config, cpu, gpu, mpi, result);
		std::cout << "Wrote results: " << config.results_output << std::endl;
	}
	return 0;
}
